const fs = require("fs"),
  path = require("path");
let currentSection = "news",
  isSearching = !1,
  currentWhen = "all";
const WHEN_LABEL = { "1d": "last 24h", "7d": "last 7 days", "30d": "last 30 days", "all": "all time" };
const postDisasterSection = document.getElementById("postDisasterSection");
const preDisasterContent = document.getElementById("preDisasterContent");
let map,
  markersLayer,
  mapInitialized = !1,
  disasterPoints = [];
const menuItems = document.querySelectorAll(".menu-item"),
  searchInput = document.getElementById("searchInput"),
  searchBtn = document.getElementById("searchBtn"),
  refreshBtn = document.getElementById("refreshBtn"),
  defaultContent = document.getElementById("defaultContent"),
  newsResults = document.getElementById("newsResults");
const reportSection = document.getElementById("reportSection"),
  sectionTitle = document.getElementById("sectionTitle"),
  resultsContainer = document.getElementById("resultsContainer"),
  reportContainer = document.getElementById("reportContainer"),
  downloadReportBtn = document.getElementById("downloadReportBtn"),
  logsContent = document.querySelector(".logs-content");
const disasterIcons = {
  flood: "🌊",
  earthquake: "🌋",
  cyclone: "🌀",
  drought: "☀️",
  landslide: "⛰️",
  tsunami: "🌊",
  wildfire: "🔥",
  default: "⚠️",
}; // Add this after your existing variable declarations
function updateSectionTitle() {
  sectionTitle.textContent =
    {
      news: "Latest News",
      "post-disaster": "Post Disaster Reports",
      "pre-disaster": "Pre Disaster Alerts",
    }[currentSection] || "News Dashboard";
}
function performSearch() {
  const query = searchInput.value.trim();
  if (!query) {
    addLog("error", "Please enter a search query.");
    return;
  }
  isSearching = !0;
  showNewsResults();
  showLoading();
  const whenForRequest = currentWhen === "all" ? null : currentWhen;
  fetch(API_CONFIG.getUrl("NEWS"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query: query, section: currentSection, when: whenForRequest }),
  })
    .then((r) => r.json())
    .then((data) => {
      displayResults(data);
      addLog(
        "info",
        `Fetched ${data.articles.length} articles for "${query}" (${WHEN_LABEL[currentWhen]})`
      );
      if (data.articles && data.articles.length) {
        fetchDisasterBrief(query, data.articles);
      } else {
        hideBrief();
      }
    })
    .catch((err) => {
      showError("Error fetching news. Please try again.");
      addLog("error", "Error fetching news: " + err.message);
      console.error("Search error:", err);
    });
}

function fetchDisasterBrief(query, articles) {
  showBriefLoading();
  fetch(API_CONFIG.getUrl("NEWS_BRIEF"), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query: query, articles: articles }),
  })
    .then((r) => r.json())
    .then((data) => {
      if (data.brief) {
        renderBrief(data.brief);
      } else {
        hideBrief();
        addLog("warning", "Disaster brief unavailable: " + (data.error || "unknown"));
      }
    })
    .catch((err) => {
      hideBrief();
      addLog("error", "Brief generation failed: " + err.message);
    });
}

const BRIEF_ICON_SVG = `
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M12 3l1.8 4.6L18 9.4l-4.2 1.8L12 16l-1.8-4.8L6 9.4l4.2-1.8L12 3z"/>
    <path d="M19 14l.9 2.1 2.1.9-2.1.9-.9 2.1-.9-2.1-2.1-.9 2.1-.9.9-2.1z"/>
    <path d="M5 16l.7 1.6 1.6.7-1.6.7-.7 1.6-.7-1.6-1.6-.7 1.6-.7.7-1.6z"/>
  </svg>`;

const BRIEF_HEADER_HTML = `
  <div class="brief-header">
    <div class="brief-icon">${BRIEF_ICON_SVG}</div>
    <span class="brief-title">Disaster Brief</span>
    <span class="brief-pill">AI Generated</span>
  </div>`;

const BRIEF_FOOTER_DOT_SVG = `<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="6"/></svg>`;

function showBriefLoading() {
  const card = document.getElementById("disasterBriefCard");
  if (!card) return;
  card.style.display = "block";
  card.innerHTML = `
    ${BRIEF_HEADER_HTML}
    <div class="brief-body">
      <div class="brief-shimmer"></div>
      <div class="brief-shimmer"></div>
      <div class="brief-shimmer short"></div>
    </div>
    <div class="brief-footer">${BRIEF_FOOTER_DOT_SVG} Synthesizing latest coverage…</div>
  `;
}

function renderBrief(text) {
  const card = document.getElementById("disasterBriefCard");
  if (!card) return;
  card.style.display = "block";
  const windowSuffix =
    currentWhen === "all" ? "" : ` · ${WHEN_LABEL[currentWhen]}`;
  card.innerHTML = `
    ${BRIEF_HEADER_HTML}
    <div class="brief-body">${escapeHtml(text).replace(/\n+/g, "<br><br>")}</div>
    <div class="brief-footer">${BRIEF_FOOTER_DOT_SVG} Generated by our smart AI${windowSuffix}</div>
  `;
}

function hideBrief() {
  const card = document.getElementById("disasterBriefCard");
  if (card) card.style.display = "none";
}
function generateReport() {
  const e = searchInput.value.trim();
  e
    ? (showReportSection(),
      (reportContainer.innerHTML =
        '<div class="loading">Generating report...</div>'),
      addLog("info", `Generating report for "${e}"`),
      fetch(API_CONFIG.getUrl("GENERATE_REPORT"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: e }),
      })
        .then((e) => e.json())
        .then((e) => {
          if (e.error)
            return (
              (reportContainer.innerHTML = `<div class="error">${e.error}</div>`),
              void addLog("error", `Report generation failed: ${e.error}`)
            );
          const t = markdownToHtml(e.report);
          ((reportContainer.innerHTML = `<div class="report-content">${t}</div>`),
            addLog("info", "Report generated successfully"));
        })
        .catch((e) => {
          ((reportContainer.innerHTML =
            '<div class="error">Error generating report. Please try again.</div>'),
            addLog("error", "Error generating report: " + e.message),
            console.error("Report error:", e));
        }))
    : addLog("error", "Please enter a search query to generate a report.");
}
const searchContainer = document.querySelector(".search-container");
function loadDefaultContent() {
  hideBrief();
  if (typeof setActiveChip === "function") setActiveChip(null);
  ((isSearching = !1),
    (searchInput.value = ""),
    (defaultContent.style.display = "block"),
    (newsResults.style.display = "none"),
    (reportSection.style.display = "none"),
    (postDisasterSection.style.display = "none"),
    (document.getElementById("postDisasterReportSection").style.display = "none"),
    (preDisasterContent.style.display = "none"),
    // Show search container for news section
    searchContainer.classList.remove("hidden"));

  // Show content area for default/news content
  document.querySelector(".content-area").style.display = "block";
}
function showNewsResults() {
  ((defaultContent.style.display = "none"),
    (newsResults.style.display = "block"),
    (reportSection.style.display = "none"),
    (postDisasterSection.style.display = "none"),
    (document.getElementById("postDisasterReportSection").style.display = "none"),
    (preDisasterContent.style.display = "none"),
    // Show search container for news section
    searchContainer.classList.remove("hidden"));

  // Show content area for news results
  document.querySelector(".content-area").style.display = "block";
}
function showReportSection() {
  ((defaultContent.style.display = "none"),
    (newsResults.style.display = "none"),
    (reportSection.style.display = "block"),
    (postDisasterSection.style.display = "none"),
    (document.getElementById("postDisasterReportSection").style.display = "none"),
    (preDisasterContent.style.display = "none"),
    // Show search container for report section
    searchContainer.classList.remove("hidden"));

  // Show content area for report section
  document.querySelector(".content-area").style.display = "block";
}
function showLoading() {
  const skeletonCount = 6;
  let html = "";
  for (let i = 0; i < skeletonCount; i++) {
    html += `
      <div class="news-article news-skeleton" style="--stagger:${i};">
        <div class="news-card-row">
          <div class="skeleton-badge"></div>
          <div class="news-card-body">
            <div class="skeleton-line skeleton-line-title"></div>
            <div class="skeleton-line skeleton-line-meta"></div>
            <div class="skeleton-line skeleton-line-pill"></div>
          </div>
        </div>
      </div>`;
  }
  resultsContainer.innerHTML = html;
}
function showError(e) {
  resultsContainer.innerHTML = `<div class="error">${e}</div>`;
}
function displayResults(e) {
  if (!e.articles || 0 === e.articles.length) {
    const isFiltered = currentWhen !== "all";
    const msg = isFiltered
      ? `No articles in the ${WHEN_LABEL[currentWhen]}. Try widening the time range.`
      : "No articles found for your search query.";
    resultsContainer.innerHTML = `<div class="error">${msg}</div>`;
    return;
  }
  resultsContainer.innerHTML = e.articles
    .map((article, idx) => renderArticleCard(article, idx))
    .join("");
}

const SOURCE_PALETTE = [
  ["#3b82f6", "#1d4ed8"],
  ["#a855f7", "#7e22ce"],
  ["#10b981", "#047857"],
  ["#f59e0b", "#b45309"],
  ["#ef4444", "#b91c1c"],
  ["#06b6d4", "#0e7490"],
  ["#ec4899", "#be185d"],
  ["#14b8a6", "#0f766e"],
  ["#8b5cf6", "#6d28d9"],
  ["#f97316", "#c2410c"],
];

function sourceInitials(name) {
  if (!name) return "?";
  const cleaned = name.replace(/^https?:\/\//, "").replace(/^www\./, "");
  const tokens = cleaned.split(/[\s.\-_/]+/).filter(Boolean);
  if (tokens.length === 1) return tokens[0].slice(0, 2).toUpperCase();
  return (tokens[0][0] + tokens[1][0]).toUpperCase();
}

function sourcePalette(name) {
  const key = name || "?";
  let hash = 0;
  for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
  return SOURCE_PALETTE[hash % SOURCE_PALETTE.length];
}

function freshnessTier(isoDate) {
  if (!isoDate) return { tier: "old", label: "Older" };
  const d = new Date(isoDate);
  if (isNaN(d.getTime())) return { tier: "old", label: "Older" };
  const days = (Date.now() - d.getTime()) / (1000 * 60 * 60 * 24);
  if (days <= 1.5) return { tier: "today", label: "Today" };
  if (days <= 7.5) return { tier: "week", label: "This week" };
  if (days <= 31) return { tier: "month", label: "This month" };
  return { tier: "old", label: "Older" };
}

function renderArticleCard(article, idx = 0) {
  const title = escapeHtml(article.title || "Untitled");
  const source = (article.source || "News Source").trim();
  const snippet = escapeHtml(article.snippet || "");
  const link = escapeHtml(article.link || "#");
  const initials = escapeHtml(sourceInitials(source));
  const [c1, c2] = sourcePalette(source);
  const fresh = freshnessTier(article.date);
  const stagger = Math.min(idx, 12);

  return `
    <article class="news-article news-article-enter" style="--stagger:${stagger};">
      <div class="news-card-row">
        <div class="source-badge" style="background: linear-gradient(135deg, ${c1}, ${c2});" aria-hidden="true">${initials}</div>
        <div class="news-card-body">
          <h3>${title}</h3>
          <div class="news-card-meta">
            <span class="freshness-dot freshness-${fresh.tier}" title="${fresh.label}"></span>
            <span class="news-card-snippet">${snippet}</span>
          </div>
          <a class="read-more-pill" href="${link}" target="_blank" rel="noopener noreferrer">
            Read article
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
          </a>
        </div>
      </div>
    </article>`;
}
function escapeHtml(e) {
  const t = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return e.replace(/[&<>"']/g, function (e) {
    return t[e];
  });
}
function addLog(e, t) {
  const n = "error" === e ? "log-error" : "log-warning",
    r = document.createElement("div");
  for (
    r.className = n,
      r.textContent = `${new Date().toLocaleTimeString()}: ${t}`,
      logsContent.prepend(r);
    logsContent.children.length > 10;

  )
    logsContent.removeChild(logsContent.lastChild);
}
function markdownToHtml(e) {
  return e
    .replace(/^# (.*$)/gm, "<h1>$1</h1>")
    .replace(/^## (.*$)/gm, "<h2>$1</h2>")
    .replace(/^### (.*$)/gm, "<h3>$1</h3>")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^- (.*$)/gm, "<li>$1</li>")
    .replace(/(\n<li>.*)+/g, "<ul>$&</ul>")
    .replace(/\n/g, "<br>");
}
function showPostDisaster() {
  defaultContent.style.display = "none";
  newsResults.style.display = "none";
  reportSection.style.display = "none";
  postDisasterSection.style.display = "block";
  // Ensure the standalone report generator view is hidden when showing the map-based post-disaster view
  document.getElementById("postDisasterReportSection").style.display = "none";
  preDisasterContent.style.display = "none";

  // Hide search container
  searchContainer.classList.add("hidden");

  // Show content area for post-disaster
  document.querySelector(".content-area").style.display = "block";

  if (!mapInitialized) {
    initMap();
    mapInitialized = true;
  }
}

// Show the standalone Post Disaster Report Generator view (no map or filters)
function showPostDisasterReport() {
  defaultContent.style.display = "none";
  newsResults.style.display = "none";
  reportSection.style.display = "none";
  postDisasterSection.style.display = "none";
  preDisasterContent.style.display = "none";

  const el = document.getElementById("postDisasterReportSection");
  if (el) el.style.display = "block";

  // Hide the top shared search container since this view has its own input
  searchContainer.classList.add("hidden");

  // Ensure content area is visible
  document.querySelector(".content-area").style.display = "block";
}
function initMap() {
  (((map = L.map("map").setView([20, 0], 2)),
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    zoom: 5,
    minZoom: 3,
    maxZoom: 18,
    maxBounds: [
      [-90, -180],
      [90, 180],
    ],
    maxBoundsViscosity: 1.0,
    attribution: "&copy; OpenStreetMap contributors",
    noWrap: true,
  }).addTo(map),
  (markersLayer = L.layerGroup().addTo(map)),
  fetch(API_CONFIG.getUrl("DISASTER_CSV"))
    .then((e) => e.json())
    .then((e) => {
      ((disasterPoints = e),
        populateCountryFilter(e),
        populateYearFilter(e),
        (document.getElementById("countryFilter").value = "India"),
        (document.getElementById("yearFilter").value = "2010"),
        filterAndRenderMarkers());
    })
    .catch((e) => {
      (addLog("error", "Failed to load disaster points: " + e.message),
        console.error("CSV load error:", e));
    }),
  document
    .getElementById("countryFilter")
    .addEventListener("change", filterAndRenderMarkers),
  document
    .getElementById("yearFilter")
    .addEventListener("change", filterAndRenderMarkers)),
    map.setMaxBounds([
      [-90, -180],
      [90, 180],
    ]));
}
function filterAndRenderMarkers() {
  const e = document.getElementById("countryFilter").value,
    t = document.getElementById("yearFilter").value;
  let n = disasterPoints;
  (e &&
    (n = n.filter(
      (t) => t.country && t.country.toLowerCase() === e.toLowerCase()
    )),
    t && (n = n.filter((e) => String(e.year) === t)),
    renderDisasterMarkers(n));
}
function renderDisasterMarkers(points) {
  markersLayer.clearLayers();
  const latlngs = [];

  points.forEach((pt) => {
    if (pt.latitude && pt.longitude) {
      latlngs.push([pt.latitude, pt.longitude]);

      const marker = L.marker([pt.latitude, pt.longitude], {
        icon: createDisasterIcon(pt.disastertype),
        title: pt.location,
      })
        .addTo(markersLayer)
        .bindPopup(
          `<b>${pt.disastertype || "Disaster"}</b><br>
         <b>Year:</b> ${pt.year || "N/A"}<br>
         <b>Location:</b> ${pt.location || "N/A"}<br>
         <b>Country:</b> ${pt.country || "N/A"}`
        );
    }
  });

  if (latlngs.length) map.fitBounds(latlngs);
}
function populateCountryFilter(e) {
  const t = new Set(e.map((e) => e.country).filter(Boolean)),
    n = document.getElementById("countryFilter");
  ((n.innerHTML = '<option value="">All Countries</option>'),
    Array.from(t)
      .sort()
      .forEach((e) => {
        const t = document.createElement("option");
        ((t.value = e), (t.textContent = e), n.appendChild(t));
      }));
}
function populateYearFilter(e) {
  const t = new Set(e.map((e) => e.year).filter(Boolean)),
    n = document.getElementById("yearFilter");
  ((n.innerHTML = '<option value="">All Years</option>'),
    Array.from(t)
      .sort()
      .forEach((e) => {
        const t = document.createElement("option");
        ((t.value = e), (t.textContent = e), n.appendChild(t));
      }));
}
function createDisasterIcon(type) {
  const icon = disasterIcons[type.toLowerCase()] || disasterIcons.default;
  return L.divIcon({
    html: `<span style="font-size: 24px;">${icon}</span>`,
    className: "disaster-marker",
    iconSize: [30, 30],
    iconAnchor: [15, 15],
  });
} // Create custom divIcon for emojis
// Attach menu and UI handlers
menuItems.forEach((e) => {
  e.addEventListener("click", function () {
    menuItems.forEach((m) => m.classList.remove("active"));
    this.classList.add("active");
    currentSection = this.getAttribute("data-section");
    updateSectionTitle();
    if (currentSection === "post-disaster") {
      showPostDisaster();
    } else if (currentSection === "post-disaster-report") {
      showPostDisasterReport();
    } else if (currentSection === "pre-disaster") {
      showPreDisaster();
    } else if (currentSection === "news") {
      isSearching || loadDefaultContent();
    } else {
      isSearching || loadDefaultContent();
    }
  });
});

searchBtn.addEventListener("click", performSearch);
searchInput.addEventListener("keypress", function (e) {
  "Enter" === e.key && performSearch();
});
searchInput.addEventListener("input", function () {
  setActiveChip(null);
});

function setActiveChip(query) {
  document.querySelectorAll(".quick-chip").forEach((chip) => {
    chip.classList.toggle("active", query !== null && chip.dataset.query === query);
  });
}

document.querySelectorAll(".quick-chip").forEach((chip) => {
  chip.addEventListener("click", function () {
    const q = this.dataset.query;
    if (!q) return;
    searchInput.value = q;
    setActiveChip(q);
    performSearch();
  });
});

document.querySelectorAll(".trending-card").forEach((card) => {
  card.addEventListener("click", function () {
    const q = this.dataset.query;
    if (!q) return;
    searchInput.value = q;
    setActiveChip(q);
    performSearch();
  });
});

(function loadFlightsTile() {
  const dot = document.getElementById("flightsDot");
  const text = document.getElementById("flightsCount");
  if (!dot || !text) return;
  fetch(API_CONFIG.getUrl("FLIGHTS"))
    .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
    .then((data) => {
      const count =
        (data && Array.isArray(data.states) && data.states.length) ||
        (data && data.count) ||
        (data && Array.isArray(data.flights) && data.flights.length) ||
        0;
      dot.classList.remove("status-dot-pending");
      dot.classList.add(count > 0 ? "status-dot-on" : "status-dot-off");
      text.textContent = count > 0 ? `${count.toLocaleString()} active` : "No data";
    })
    .catch(() => {
      dot.classList.remove("status-dot-pending");
      dot.classList.add("status-dot-off");
      text.textContent = "Offline";
    });
})();

function setActiveTimeOption(when) {
  currentWhen = when;
  document.querySelectorAll(".time-option").forEach((opt) => {
    const isActive = opt.dataset.when === when;
    opt.classList.toggle("active", isActive);
    opt.setAttribute("aria-selected", isActive ? "true" : "false");
  });
}

document.querySelectorAll(".time-option").forEach((opt) => {
  opt.addEventListener("click", function () {
    const w = this.dataset.when;
    if (!w || w === currentWhen) return;
    setActiveTimeOption(w);
    if (searchInput.value.trim()) {
      performSearch();
    }
  });
});

// Standalone Post Disaster Report generator wiring
(function() {
  const postReportInput = document.getElementById("postReportInput");
  const postReportGenerateBtn = document.getElementById("postReportGenerateBtn");
  if (postReportInput) {
    // Pressing Enter in the input triggers Generate Report for the Post Disaster generator
    postReportInput.addEventListener("keypress", function(e) {
      if ("Enter" === e.key) {
        searchInput.value = postReportInput.value || "";
        generateReport();
      }
    });
  }
  if (postReportGenerateBtn && postReportInput) {
    postReportGenerateBtn.addEventListener("click", function() {
      searchInput.value = postReportInput.value || "";
      generateReport();
    });
  }
})();

refreshBtn.addEventListener("click", function () {
  isSearching ? performSearch() : loadDefaultContent();
});

downloadReportBtn.addEventListener("click", function () {
  const e = searchInput.value.trim() || "disaster_report",
    t = reportContainer.querySelector(".report-content");
  if (!t) return void addLog("error", "No report available to download.");
  const n = t.innerText,
    r = `disaster_report_${e.replace(/\s+/g, "_")}.md`,
    o = path.join(
      process.env.HOME || process.env.USERPROFILE,
      "Downloads",
      r
    );
  try {
    (fs.writeFileSync(o, n), addLog("info", "Report downloaded successfully to Downloads folder"));
  } catch (e) {
    addLog("error", `Download failed: ${e.message}`);
  }
});
(document.addEventListener("DOMContentLoaded", function () {
  const e = document.getElementById("sidebarTitle"),
    t = document.getElementById("screenDropdown"),
    n = document.querySelector(".dropdown-arrow"),
    r = document.querySelectorAll(".dropdown-item"),
    o = document.querySelector(".sidebar-title-container");
  (o.addEventListener("click", function (e) {
    (e.preventDefault(),
      e.stopPropagation(),
      t.classList.toggle("show"),
      n.classList.toggle("rotated"));
  }),
    window.addEventListener("click", function (e) {
      o.contains(e.target) ||
        (t.classList.remove("show"), n.classList.remove("rotated"));
    }),
    t.addEventListener("click", function (e) {
      e.stopPropagation();
    }),
    r.forEach((o) => {
      o.addEventListener("click", function (o) {
        o.stopPropagation();
        const s = this.getAttribute("data-screen"),
          a = this.querySelector("span").textContent;
        (r.forEach((e) => e.classList.remove("active")),
          this.classList.add("active"),
          (e.textContent = a),
          t.classList.remove("show"),
          n.classList.remove("rotated"),
          (function (e) {
            switch (e) {
              case "monitoring":
                window.location.href = "../monitoring/monitoring.html";
                break;
              case "disaster":
                console.log("Already on Disaster Analysis screen");
                break;
              case "analytics":
                window.location.href = "../analysis/analysis.html";
                break;
            }
          })(s));
      });
    }));
}),
  updateSectionTitle(),
  loadDefaultContent(),
  document.querySelector(".expand-btn").addEventListener("click", function () {
    const e = document.querySelector(".bottom-panel");
    "300px" === e.style.height
      ? ((e.style.height = "140px"), (this.textContent = "Expand ▲"))
      : ((e.style.height = "300px"), (this.textContent = "Collapse ▼"));
  }),
  document
    .getElementById("generateAnalysisBtn")
    .addEventListener("click", async function () {
      const analysisResult = document.getElementById("analysisResult");
      const analysisContent = document.getElementById("analysisContent");

      // Get currently displayed disasters
      const currentDisasters = [];
      markersLayer.eachLayer((marker) => {
        const position = marker.getLatLng();
        const popup = marker.getPopup();
        currentDisasters.push({
          latitude: position.lat,
          longitude: position.lng,
          details: popup.getContent(),
        });
      });

      analysisContent.innerHTML =
        '<div class="loading">Generating analysis...</div>';
      analysisResult.style.display = "block";

      try {
        const response = await fetch(API_CONFIG.getUrl("ANALYZE_DISASTERS"), {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            disasters: currentDisasters,
            country: document.getElementById("countryFilter").value,
            year: document.getElementById("yearFilter").value,
          }),
        });

        const data = await response.json();
        analysisContent.innerHTML = `
      <div class="analysis-content">
        ${markdownToHtml(data.analysis)}
      </div>
    `;
        addLog("info", "Generated disaster analysis report");
      } catch (error) {
        analysisContent.innerHTML =
          '<div class="error">Failed to generate analysis</div>';
        addLog("error", "Failed to generate analysis: " + error.message);
      }
    }));

// --- Pre-Disaster Map (like Post Disaster, but shows weather on click) ---
let preDisasterMap, preDisasterWeatherMarker;

function showPreDisaster() {
  defaultContent.style.display = "none";
  newsResults.style.display = "none";
  reportSection.style.display = "none";
  postDisasterSection.style.display = "none";
  document.getElementById("postDisasterReportSection").style.display = "none";
  preDisasterContent.style.display = "block";

  // Hide search container
  searchContainer.classList.add("hidden");

  // Hide content area for pre-disaster
  document.querySelector(".content-area").style.display = "none";

  document.getElementById("preWeatherHeadline").innerHTML = "";
  if (!preDisasterMap) initPreDisasterMap();
}

function hidePreDisaster() {
  preDisasterContent.style.display = "none";
  document.getElementById("preWeatherHeadline").innerHTML = "";

  // Show content area when leaving pre-disaster
  document.querySelector(".content-area").style.display = "block";
}

function initPreDisasterMap() {
  preDisasterMap = L.map("preDisasterMap").setView([20, 0], 2);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    zoom: 5,
    minZoom: 3,
    maxZoom: 18,
    maxBounds: [
      [-90, -180],
      [90, 180],
    ],
    attribution: "&copy; OpenStreetMap contributors",
    noWrap: true,
  }).addTo(preDisasterMap);

  preDisasterMap.setMaxBounds([
    [-90, -180],
    [90, 180],
  ]);
  preDisasterMap.on("click", function (e) {
    const { lat, lng } = e.latlng;
    if (preDisasterWeatherMarker)
      preDisasterMap.removeLayer(preDisasterWeatherMarker);
    preDisasterWeatherMarker = L.marker([lat, lng]).addTo(preDisasterMap);
    document.getElementById("preWeatherHeadline").innerHTML =
      '<div class="loading">Fetching weather...</div>';
    fetch(
      `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,precipitation,weather_code,windspeed_10m,cloud_cover&timezone=auto`
    )
      .then((res) => res.json())
      .then((data) => {
        const w = data.current;
        const headline = `
          <div>
            <span class="weather-temp">Weather at (${lat.toFixed(2)}, ${lng.toFixed(2)}):
            ${w.temperature_2m}°C, ${w.precipitation}mm rain, ${w.windspeed_10m}km/h wind, ${w.cloud_cover}% clouds.</span>
            <span class="weather-ai-summary"><b>AI:</b> ${getAISummary(w)}</span>
          </div>
        `;
        document.getElementById("preWeatherHeadline").innerHTML = headline;
      })
      .catch(() => {
        document.getElementById("preWeatherHeadline").innerHTML =
          '<div class="error">Failed to fetch weather data.</div>';
      });
  });
}

// Hardcoded AI summary logic (demo)
function getAISummary(w) {
  if (w.precipitation > 20)
    return "⚠️ High risk of flooding due to heavy rainfall.";
  if (w.temperature_2m > 40)
    return "⚠️ Extreme heat detected. Possible heatwave.";
  if (w.windspeed_10m > 60) return "⚠️ Severe wind speeds. Storm risk present.";
  if (w.cloud_cover > 90) return "Heavy cloud cover, possible storms.";
  return "No immediate disaster risk detected.";
}

// (menu click handling is attached earlier in the file)
